### ISSUE TITLE
Corrupted HD5 files

### ISSUE THREAD

**Issue by fbemm** [minoTour/minoTour#2]
Some of our runs will not import and crash with the following error:

2015-10-27 17:58:32 CACHED: 25087 PROCESSED: 24090
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140532754958080:
  #000: ../../../src/H5O.c line 242 in H5Oopen(): no name
    major: Invalid arguments to routine
    minor: Bad value
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "minup.py", line 2234, in processfiles
    process_fast5(fast5file, self.hdf, self.db_name, cursor)
  File "minup.py", line 561, in process_fast5
    configdata=hdf[basecalldirconfig]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2424)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 164, in __getitem**
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2424)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip_build_root/h5py/h5py/h5o.c:3516)
ValueError: No name (No name)

stopping monitor.
setting run12 to an inactive run
finished.

HDF5: infinite loop closing library
      D,G,A,S,T,F,FD,P,FD,P,FD,P,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

I guess something is wrong with the fast5 files. We base-called everything again but the error persists.

Any ideas?

**Comment by mattloose** [comment]
Hi - yeah - this is a problem we have seen a little recently. We are working on a fix, but it will be incorporated into the next point update alongside a number of other important fixes.

In the meantime, this version of minUP for windows (are you running on windows?) should let you get past these reads without error.
https://drive.google.com/file/d/0B1ZOYiRdAG17Zm11a2xwLWdFelE/view?usp=sharing

Hope this helps. We hope to have the new version out in the next couple of days.

**Comment by fbemm** [comment]
Hi Matt, thanks for the fast response. I am not using Windows ;(

**Comment by mattloose** [comment]
In that case - try this one... https://drive.google.com/open?id=0B1ZOYiRdAG17czVpTHVPQ2ptXzg

Should do what you need! If it doesn't please let me know and I'll get it sorted.

**Comment by fbemm** [comment]
The new version works! Thanks a lot!
